#!/usr/bin/env bash

INPUT=$1
OUTPUT=$2
TMP_PREFIX=$3

I_FILENAME=$(basename $INPUT)
O_FILENAME=$(basename $OUTPUT)
TMP_DIR=$TMP_PREFIX
mkdir -p $TMP_DIR
aws s3 cp $INPUT $TMP_DIR/$I_FILENAME

OUTPUT_LOCAL=$TMP_DIR/$O_FILENAME
INPUT_LOCAL=$TMP_DIR/$I_FILENAME

samtools sort -m 8G -o $OUTPUT_LOCAL -T $TMP_PREFIX -@ 4 $INPUT_LOCAL

aws s3 cp $OUTPUT_LOCAL $OUTPUT
